var searchData=
[
  ['vcoroutineschedule_26935',['vCoRoutineSchedule',['../group__v_co_routine_schedule.html',1,'']]],
  ['vqueuedelete_26936',['vQueueDelete',['../group__v_queue_delete.html',1,'']]],
  ['vsemaphorecreatebinary_26937',['vSemaphoreCreateBinary',['../group__v_semaphore_create_binary.html',1,'']]],
  ['vsemaphoredelete_26938',['vSemaphoreDelete',['../group__v_semaphore_delete.html',1,'']]],
  ['vstreambufferdelete_26939',['vStreamBufferDelete',['../group__v_stream_buffer_delete.html',1,'']]],
  ['vtaskdelay_26940',['vTaskDelay',['../group__v_task_delay.html',1,'']]],
  ['vtaskdelayuntil_26941',['vTaskDelayUntil',['../group__v_task_delay_until.html',1,'']]],
  ['vtaskdelete_26942',['vTaskDelete',['../group__v_task_delete.html',1,'']]],
  ['vtaskendscheduler_26943',['vTaskEndScheduler',['../group__v_task_end_scheduler.html',1,'']]],
  ['vtaskgetinfo_26944',['vTaskGetInfo',['../group__v_task_get_info.html',1,'']]],
  ['vtaskgetruntimestats_26945',['vTaskGetRunTimeStats',['../group__v_task_get_run_time_stats.html',1,'']]],
  ['vtasklist_26946',['vTaskList',['../group__v_task_list.html',1,'']]],
  ['vtaskpriorityset_26947',['vTaskPrioritySet',['../group__v_task_priority_set.html',1,'']]],
  ['vtaskresume_26948',['vTaskResume',['../group__v_task_resume.html',1,'']]],
  ['vtaskresumefromisr_26949',['vTaskResumeFromISR',['../group__v_task_resume_from_i_s_r.html',1,'']]],
  ['vtaskstartscheduler_26950',['vTaskStartScheduler',['../group__v_task_start_scheduler.html',1,'']]],
  ['vtasksuspend_26951',['vTaskSuspend',['../group__v_task_suspend.html',1,'']]],
  ['vtasksuspendall_26952',['vTaskSuspendAll',['../group__v_task_suspend_all.html',1,'']]]
];
